# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9646ba7fc91a0246f2b4b26da6f62b3a2596e4eb6066c7fa9a366a4425e4009de64af74bb7948929f40baaf5d9fc87d4afbb2064d182857ebf4759db6378245a

test:
  secret_key_base: a27f26908c6278bae507d59c84c99f29dd386d9517a19165e2ccdd340fb788fb3752186c5f15711758ca5faa734e933e5338057485916ff40f8656e0e2d0914f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
